# -*- coding: utf-8 -*-
"""900 images 300 augmentation 4/27/2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OqvZZjJZLxnte80NpSBZDRZcqTKx6BSz
"""

# ==============================================
# Skin Disease Classification (EfficientNetB0)
# ==============================================

# ----------------------------
# 2. Imports & Sub-module Definitions
# ----------------------------
import os
import shutil
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, roc_curve, auc
from sklearn.preprocessing import label_binarize

# Suppress TF logs before importing TF
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import tensorflow as tf

import datetime

# Define aliases to help the IDE resolve "Keras" paths
layers = tf.keras.layers
models = tf.keras.models
callbacks = tf.keras.callbacks
preprocessing = tf.keras.preprocessing
utils = tf.keras.utils
EfficientNetB0 = tf.keras.applications.EfficientNetB0
preprocess_input = tf.keras.applications.efficientnet.preprocess_input

# Optional: Enable memory growth to prevent the GPU from hogging all RAM at once
gpu_devices = tf.config.list_physical_devices('GPU')
if gpu_devices:
    try:
        tf.config.experimental.set_memory_growth(gpu_devices[0], True)
    except RuntimeError as e:
        print(e)

# ----------------------------
# 3. Dataset Path (Corrected for your folder names)
# ----------------------------
base_path = '/Users/iancheung/Documents/Skin_Disease'
# This matches your 'ls' output
dataset_dir = os.path.join(base_path, 'DataSet') 
original_dataset_path = dataset_dir

# Result tracking
results_root = os.path.join(base_path, 'Results')
os.makedirs(results_root, exist_ok=True)

# Important: Use only ONE timestamped directory per run
timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
current_run_dir = os.path.join(results_root, f'run_{timestamp}')
os.makedirs(current_run_dir, exist_ok=True)

# Path for the split folders
train_dir = os.path.join(base_path, 'train_split')
val_dir = os.path.join(base_path, 'val_split')

# ----------------------------
# 4. Parameters
# ----------------------------
img_height, img_width = 224, 224
batch_size = 32
AUTOTUNE = tf.data.AUTOTUNE
# ----------------------------
# 5. Count Images Per Class
# ----------------------------
# Detect the new classes (Atopic_Dermatitis, Tinea, etc.)
class_names = sorted([d for d in os.listdir(dataset_dir) if os.path.isdir(os.path.join(dataset_dir, d))])
print(f"Detected classes: {class_names}")

class_counts = {}

for class_name in class_names:
    class_path = os.path.join(dataset_dir, class_name)

    # Count only image files
    num_images = len([
        f for f in os.listdir(class_path)
        if f.lower().endswith(('.png', '.jpg', '.jpeg'))
    ])

    class_counts[class_name] = num_images

# ----------------------------
# 6. Print Table
# ----------------------------
df_counts = pd.DataFrame(
    list(class_counts.items()),
    columns=["Class", "Number of Samples"]
)

print("\n📊 Dataset Distribution:\n")
print(df_counts)

"""### 7. Data Augmentation to Reach 10000 Images Per Class

To address potential class imbalance and ensure sufficient training data, we will augment the dataset so that each class has at least 10000 images (training data only). This involves generating new images from existing ones using transformations like horizontal flipping, rotation, and zooming, and saving them back to the dataset directory.
"""

import os
import shutil
import random
import tensorflow as tf
from sklearn.model_selection import train_test_split

# 1. Setup paths for split
train_dir = os.path.join(base_path, 'train_split')
val_dir = os.path.join(base_path, 'val_split')

# 2. Perform the Split (only if not already done)
if not os.path.exists(train_dir):
    print("Splitting original data into 80/20 Train/Val folders...")
    for class_name in class_names:
        os.makedirs(os.path.join(train_dir, class_name), exist_ok=True)
        os.makedirs(os.path.join(val_dir, class_name), exist_ok=True)
        
        orig_class_path = os.path.join(original_dataset_path, class_name)
        images = [f for f in os.listdir(orig_class_path) if f.lower().endswith(('.jpg', '.jpeg', '.png'))]
        
        train_imgs, val_imgs = train_test_split(images, test_size=0.2, random_state=123)
        
        for img in train_imgs:
            shutil.copy(os.path.join(orig_class_path, img), os.path.join(train_dir, class_name, img))
        for img in val_imgs:
            shutil.copy(os.path.join(orig_class_path, img), os.path.join(val_dir, class_name, img))

# Define the transformations for the physical files saved to disk
data_augmentation_for_saving = tf.keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.2),
    layers.RandomZoom(0.1),
])

# 3. Augment ONLY the training directory
target_per_class = 600
print(f"Augmenting training set to {target_per_class} images per class...")

for class_name in class_names:
    curr_train_path = os.path.join(train_dir, class_name)
    train_files = [f for f in os.listdir(curr_train_path) if f.lower().endswith(('.jpg', '.jpeg', '.png'))]
    
    num_to_add = target_per_class - len(train_files)
    
    if num_to_add > 0:
        print(f"  Adding {num_to_add} images to training class: {class_name}")
        for i in range(num_to_add):
            ref_img_path = os.path.join(curr_train_path, random.choice(train_files))
            
            # Load and augment
            img = preprocessing.image.load_img(ref_img_path, target_size=(img_height, img_width))
            img_array = preprocessing.image.img_to_array(img)
            img_array = tf.expand_dims(img_array, 0)

            aug_batch = data_augmentation_for_saving(img_array, training=True)
            aug_img = aug_batch[0].numpy().astype(np.uint8)

            # Save back into the training folder
            aug_pil = preprocessing.image.array_to_img(aug_img)
            aug_pil.save(os.path.join(curr_train_path, f"aug_{i}_{os.path.basename(ref_img_path)}"))

# ----------------------------
# 7b. Pure Subsampling Logic (Exactly 12 Original Images)
# ----------------------------
target_val_per_class = 12
print(f"Selecting exactly {target_val_per_class} PURE original images per class...")

for class_name in class_names:
    curr_val_path = os.path.join(val_dir, class_name)
    
    # 1. Identify only original files (ignore anything we previously augmented)
    all_files = [f for f in os.listdir(curr_val_path) if f.lower().endswith(('.jpg', '.jpeg', '.png'))]
    original_val_files = [f for f in all_files if not f.startswith('aug_val_')]
    
    # 2. Clear the folder completely to start fresh
    for f in all_files:
        os.remove(os.path.join(curr_val_path, f))
    
    # 3. Randomly select exactly 20 from the original split
    if len(original_val_files) >= target_val_per_class:
        selected_files = random.sample(original_val_files, target_val_per_class)
        
        # 4. Copy them back in
        for f in selected_files:
            # We use shutil.copy because we are pulling from the organized_dataset 
            # to ensure we have the originals if we accidentally deleted them
            src = os.path.join(original_dataset_path, class_name, f)
            shutil.copy(src, os.path.join(curr_val_path, f))
            
        print(f"  ✅ {class_name}: Successfully sampled {target_val_per_class} original images.")
    else:
        # This shouldn't happen with 20, but it's a good safety check
        print(f"  ❌ ERROR: {class_name} only has {len(original_val_files)} images!")

# 4. Load the datasets separately (No validation_split needed here)
# Load Training (Already augmented on disk)
# Load Training
train_ds = utils.image_dataset_from_directory(
    train_dir,
    image_size=(img_height, img_width),
    batch_size=batch_size,
    shuffle=True
)

# Load Validation (Untouched original images)
val_ds = tf.keras.utils.image_dataset_from_directory(
    val_dir,
    image_size=(img_height, img_width),
    batch_size=batch_size,
    shuffle=False 
)

class_names = train_ds.class_names
num_classes = len(class_names)
dataset_dir = train_dir
print(f"Dataset directory updated to: {train_dir}")

"""### 8. Updated Dataset Distribution After Augmentation

Now, let's re-count the images to confirm the new distribution per class after augmentation.
"""

# Re-count images per class after augmentation
class_names = sorted(os.listdir(dataset_dir))

class_counts_augmented = {}

for class_name in class_names:
    class_path = os.path.join(dataset_dir, class_name)
    num_images = len([
        f for f in os.listdir(class_path)
        if f.lower().endswith(('.png', '.jpg', '.jpeg'))
    ])
    class_counts_augmented[class_name] = num_images

# Create DataFrame for updated counts
df_counts_augmented = pd.DataFrame(
    list(class_counts_augmented.items()),
    columns=["Class", "Number of Samples"]
)

print("\n📊 Updated Dataset Distribution (After Augmentation):\n")
print(df_counts_augmented)

# Plotting the updated bar chart
plt.figure(figsize=(10, 6))
colors = plt.cm.tab10(range(len(df_counts_augmented)))
plt.bar(df_counts_augmented["Class"], df_counts_augmented["Number of Samples"], color=colors)
plt.xticks(rotation=45, ha='right')
plt.title("Number of Samples per Class (After Augmentation)")
plt.xlabel("Class")
plt.ylabel("Number of Images")
plt.tight_layout()
#plt.show()

# ----------------------------
# 7. Plot Bar Chart
# ----------------------------
plt.figure()

colors = plt.cm.tab10(range(len(df_counts)))  # nice distinct colors

plt.bar(df_counts["Class"], df_counts["Number of Samples"], color=colors)

plt.xticks(rotation=45, ha='right')
plt.title("Number of Samples per Class")
plt.xlabel("Class")
plt.ylabel("Number of Images")

plt.tight_layout()
fig = plt.gcf()
fig.savefig(os.path.join(current_run_dir, "class_distribution.png"), dpi=300, bbox_inches='tight')
#plt.show()

class_names = train_ds.class_names
num_classes = len(class_names)

print("\n✅ Classes detected:", class_names)
print("✅ Number of classes:", num_classes)

# 1. Define the augmentation layers
data_augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.2),
])

def count_images(dataset):
    count = 0
    for images, labels in dataset:
        count += images.shape[0]
    return count

# 2. Define a single function to handle the logic
def prepare_ds(ds, augment=False):
    # Apply Augmentation first (to raw pixels)
    if augment:
        ds = ds.map(lambda x, y: (data_augmentation(x, training=True), y), 
                    num_parallel_calls=AUTOTUNE)
    
    # Apply EfficientNet Preprocessing LAST (to prepare for the model)
    ds = ds.map(lambda x, y: (preprocess_input(x), y), 
                num_parallel_calls=AUTOTUNE)
    
    return ds.prefetch(buffer_size=AUTOTUNE)

# 3. Use the function
train_ds = prepare_ds(train_ds, augment=True)
val_ds = prepare_ds(val_ds, augment=False) # No augmentation for validation!

# ----------------------------
# 7. Preprocessing (EfficientNet)
# ----------------------------

# ----------------------------
# 8. Build Model (Better Fine-Tuning Strategy)
# ----------------------------
# Build Model
base_model = EfficientNetB0(
    weights='imagenet',
    include_top=False,
    input_shape=(img_height, img_width, 3)
)

# 🔒 Freeze most layers first (important!)
for layer in base_model.layers[:-50]:
    layer.trainable = False

# Unfreeze top layers only
for layer in base_model.layers[-50:]:
    layer.trainable = True

# Build full model
x = base_model.output
x = layers.GlobalAveragePooling2D()(x)
x = layers.BatchNormalization()(x)  # improves stability
x = layers.Dense(256, activation='relu')(x)
x = layers.Dropout(0.5)(x)
outputs = layers.Dense(num_classes, activation='softmax')(x)

model = tf.keras.Model(inputs=base_model.input, outputs=outputs)

# Compile
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# model.summary()

# ----------------------------
# 9. Callbacks (VERY IMPORTANT)
# ----------------------------
callbacks = [
    tf.keras.callbacks.EarlyStopping(
        patience=5,
        restore_best_weights=True,
        verbose=1
    ),
    tf.keras.callbacks.ReduceLROnPlateau(
        factor=0.3,
        patience=3,
        verbose=1
    )
]

# ----------------------------
# 10. Train Model
# ----------------------------
history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=50,
    callbacks=callbacks,
    verbose=2
)

"""**Count Samples Before and After Augmentation**"""

# ----------------------------
# Count number of samples BEFORE augmentation
# ----------------------------
# ✅ NEW SAFE WAY
num_samples_train = count_images(train_ds)
num_samples_val = count_images(val_ds)

print(f"Number of training samples: {num_samples_train}")
print(f"Number of validation samples: {num_samples_val}")

print(f"Number of training samples BEFORE augmentation: {num_samples_train}")
print(f"Number of validation samples: {num_samples_val}")

# ----------------------------
# 9. Extract predictions and true labels
# ----------------------------
def get_labels_and_predictions(dataset, model):
    y_true = []
    y_pred = []
    for images, labels in dataset:
        preds = model.predict(images)
        y_true.extend(labels.numpy())
        y_pred.extend(np.argmax(preds, axis=1))
    return np.array(y_true), np.array(y_pred)

# For training dataset
y_true_train, y_pred_train = get_labels_and_predictions(train_ds, model)

# For validation dataset
y_true_val, y_pred_val = get_labels_and_predictions(val_ds, model)

# ----------------------------
# Define metrics_df function
# ----------------------------
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

def metrics_df(y_true, y_pred, dataset_name):
    """Compute key classification metrics and return as DataFrame."""
    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred, average='weighted')
    recall = recall_score(y_true, y_pred, average='weighted')
    f1 = f1_score(y_true, y_pred, average='weighted')

    # Optional: confusion matrix display
    cm = confusion_matrix(y_true, y_pred)
    print(f"\nConfusion Matrix ({dataset_name}):\n", cm)

    # Return DataFrame with metrics
    df = pd.DataFrame({
        'Dataset': [dataset_name],
        'Accuracy': [accuracy],
        'Precision': [precision],
        'Recall': [recall],
        'F1-Score': [f1]
    })
    return df

df_metrics_train = metrics_df(y_true_train, y_pred_train, "Training")
df_metrics_val   = metrics_df(y_true_val, y_pred_val, "Validation")

print(pd.concat([df_metrics_train, df_metrics_val]))

# ----------------------------
# 11. Save Metrics Table and Picture
# ----------------------------

# 1. Combine the metrics into one table
df_all_metrics = pd.concat([df_metrics_train, df_metrics_val], ignore_index=True)

# 2. Save the table as a CSV file
df_all_metrics.to_csv(os.path.join(current_run_dir,"final_classification_metrics.csv"), index=False)
print("\n✅ Table saved as: final_classification_metrics.csv")

# 3. Create a bar chart comparing Training vs Validation
plt.figure(figsize=(10, 6))

# Melt the dataframe to make it suitable for a grouped bar chart
df_melted = df_all_metrics.melt(id_vars="Dataset", var_name="Metric", value_name="Score")

sns.barplot(data=df_melted, x="Metric", y="Score", hue="Dataset", palette="muted")

plt.ylim(0, 1.1) # Set Y axis from 0 to 1.1 for clarity
plt.title("Comparison of Training vs Validation Metrics", fontsize=15)
plt.ylabel("Score (0.0 - 1.0)")
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.legend(loc='lower right')

# 4. Save the plot as a high-resolution image
plt.savefig(os.path.join(current_run_dir,"metrics_comparison_chart.png"), dpi=300, bbox_inches='tight')
print("✅ Chart saved as: metrics_comparison_chart.png")

# plt.show()

# ----------------------------
# 11. Final Thesis-Ready Output Generation
# ----------------------------

# 1. Generate the Metrics for the Balanced Sets
# We use the dataset names to clarify that these are the augmented versions
df_metrics_train = metrics_df(y_true_train, y_pred_train, "Training")
df_metrics_val   = metrics_df(y_true_val, y_pred_val, "Validation (Balanced 12 per class)")

# 2. Combine into a single Master Table
df_final_report = pd.concat([df_metrics_train, df_metrics_val], ignore_index=True)

# 3. Save as CSV for Excel/LaTeX import
df_final_report.to_csv(os.path.join(current_run_dir,"balanced_capstone_metrics.csv"), index=False)

# 4. Create a High-Resolution Comparison Plot
plt.figure(figsize=(12, 6))
df_melted = df_final_report.melt(id_vars="Dataset", var_name="Metric", value_name="Score")

# Use a professional color palette (e.g., 'deep' or 'colorblind')
sns.barplot(data=df_melted, x="Metric", y="Score", hue="Dataset", palette="deep")

plt.ylim(0, 1.1)
plt.title("Model Performance: Balanced Training (10k/class) vs. Pure Balanced Validation (20/class)", fontsize=14)
plt.ylabel("Performance Score")
plt.axhline(0.80, color='red', linestyle='--', alpha=0.3, label='80% Threshold') # Visual benchmark
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.savefig(os.path.join(current_run_dir,"final_performance_comparison.png"), dpi=300)
print("\n✅ Thesis-ready files generated: 'balanced_capstone_metrics.csv' and 'final_performance_comparison.png'")

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

def plot_confusion_matrices(y_true_train, y_pred_train, y_true_val, y_pred_val, class_names):
    """
    Plot training and validation confusion matrices as side-by-side subplots.
    Returns the figure object for saving.
    """
    # Compute confusion matrices
    cm_train = confusion_matrix(y_true_train, y_pred_train)
    cm_val = confusion_matrix(y_true_val, y_pred_val)

    # Set up subplots
    fig, axes = plt.subplots(1, 2, figsize=(18, 7))

    # Training CM
    sns.heatmap(
        cm_train, annot=True, fmt='d', cmap='Blues',
        xticklabels=class_names, yticklabels=class_names,
        ax=axes[0]
    )
    axes[0].set_title("Training Confusion Matrix", fontsize=14)
    axes[0].set_xlabel("Predicted Label", fontsize=12)
    axes[0].set_ylabel("True Label", fontsize=12)
    axes[0].tick_params(axis='x', labelsize=10, rotation=45)
    axes[0].tick_params(axis='y', labelsize=10, rotation=0)

    # Validation CM
    sns.heatmap(
        cm_val, annot=True, fmt='d', cmap='Greens',
        xticklabels=class_names, yticklabels=class_names,
        ax=axes[1]
    )
    axes[1].set_title("Validation Confusion Matrix", fontsize=14)
    axes[1].set_xlabel("Predicted Label", fontsize=12)
    axes[1].set_ylabel("True Label", fontsize=12)
    axes[1].tick_params(axis='x', labelsize=10, rotation=45)
    axes[1].tick_params(axis='y', labelsize=10, rotation=0)

    fig.tight_layout()  # fix spacing
    return fig  # return figure for saving

# ----------------------------
# Example usage
# ----------------------------
fig = plot_confusion_matrices(y_true_train, y_pred_train, y_true_val, y_pred_val, class_names)

# Save figure
fig.savefig(os.path.join(current_run_dir,"confusion_matrix_training_testing.png"), dpi=300, bbox_inches='tight')

#plt.show()

# ----------------------------
# 10. Accuracy & Loss Plots
# ----------------------------
plt.figure(figsize=(7,4))

plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Val Accuracy')
plt.title('Accuracy Over Epochs')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.title('Loss Over Epochs')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.savefig(os.path.join(current_run_dir,'accuracy_loss.png'))
#plt.show()

import matplotlib.pyplot as plt
import tensorflow as tf
import random

# ----------------------------
# Parameters
# ----------------------------
samples_per_class = 1       # one image per class
img_height, img_width = 224, 224  # EfficientNet input size

# ----------------------------
# Function to extract one sample per class from training dataset
# ----------------------------
def get_one_sample_from_dataset(dataset, class_index):
    """Return one image from a given class index in the dataset."""
    for batch_images, batch_labels in dataset:
        batch_labels_np = batch_labels.numpy()
        batch_images_np = batch_images.numpy()
        for i, label in enumerate(batch_labels_np):
            if label == class_index:
                return batch_images_np[i]
    return None

# ----------------------------
# Plotting as a square matrix
# ----------------------------
num_classes = len(class_names)
cols = min(5, num_classes)              # max 5 columns
rows = (num_classes + cols - 1) // cols # compute required rows

fig, axes = plt.subplots(rows, cols, figsize=(cols*3, rows*3))

# Flatten axes for easy iteration
axes = axes.flatten()

for idx, class_name in enumerate(class_names):
    img = get_one_sample_from_dataset(train_ds, idx)
    if img is None: continue
    
    # Just clip/scale for visualization since it's already preprocessed
    display_img = ((img - img.min()) / (img.max() - img.min()) * 255).astype("uint8")
    axes[idx].imshow(display_img)
    axes[idx].set_title(f"{class_name}", fontsize=8)
    axes[idx].axis("off")

# Hide any unused axes
for j in range(idx+1, len(axes)):
    axes[j].axis("off")

plt.suptitle("One Sample per Class (Preprocessed for EfficientNet)", fontsize=14)
plt.tight_layout()

# Save the figure
fig.savefig(os.path.join(current_run_dir,"sample_images_matrix.png"), dpi=300, bbox_inches='tight')
#plt.show()

def plot_roc_subplots(train_ds, val_ds, model, num_classes):
    """
    Plot ROC curves for training and validation datasets side by side.

    Each dataset gets its own subplot.
    """
    import matplotlib.pyplot as plt
    from sklearn.metrics import roc_curve, auc
    from sklearn.preprocessing import label_binarize
    import numpy as np

    # Helper to get true labels and predicted probabilities
    y_true_train, y_probs_train = get_probabilities_and_labels(train_ds, model)
    y_true_val, y_probs_val = get_probabilities_and_labels(val_ds, model)

    # Create subplots
    fig, axes = plt.subplots(1, 2, figsize=(10, 5))

    # ----------------------------
    # Training ROC
    # ----------------------------
    ax = axes[0]
    if num_classes == 2:
        fpr, tpr, _ = roc_curve(y_true_train, y_probs_train[:, 1])
        roc_auc = auc(fpr, tpr)
        ax.plot(fpr, tpr, lw=2, label=f"AUC = {roc_auc:.3f}")
    else:
        y_true_bin = label_binarize(y_true_train, classes=range(num_classes))
        for i in range(num_classes):
            fpr, tpr, _ = roc_curve(y_true_bin[:, i], y_probs_train[:, i])
            roc_auc = auc(fpr, tpr)
            ax.plot(fpr, tpr, lw=2, label=f"Class {i} (AUC={roc_auc:.3f})")

    ax.plot([0, 1], [0, 1], 'k--', lw=1)
    ax.set_title("Training ROC")
    ax.set_xlabel("False Positive Rate")
    ax.set_ylabel("True Positive Rate")
    ax.legend(fontsize=8)
    ax.grid(True)

    # ----------------------------
    # Validation ROC
    # ----------------------------
    ax = axes[1]
    if num_classes == 2:
        fpr, tpr, _ = roc_curve(y_true_val, y_probs_val[:, 1])
        roc_auc = auc(fpr, tpr)
        ax.plot(fpr, tpr, lw=2, label=f"AUC = {roc_auc:.3f}")
    else:
        y_true_bin = label_binarize(y_true_val, classes=range(num_classes))
        for i in range(num_classes):
            fpr, tpr, _ = roc_curve(y_true_bin[:, i], y_probs_val[:, i])
            roc_auc = auc(fpr, tpr)
            ax.plot(fpr, tpr, lw=2, label=f"Class {i} (AUC={roc_auc:.3f})")

    ax.plot([0, 1], [0, 1], 'k--', lw=1)
    ax.set_title("Validation ROC")
    ax.set_xlabel("False Positive Rate")
    ax.set_ylabel("True Positive Rate")
    ax.legend(fontsize=8)
    ax.grid(True)

    plt.tight_layout()
    return fig

def get_probabilities_and_labels(dataset, model):
    import numpy as np
    y_true = []
    y_pred_probs = []

    for images, labels in dataset:
        probs = model.predict(images, verbose=0)
        y_true.append(labels.numpy())
        y_pred_probs.append(probs)

    y_true = np.concatenate(y_true)
    y_pred_probs = np.concatenate(y_pred_probs)

    return y_true, y_pred_probs

# Generate the ROC figure
fig = plot_roc_subplots(train_ds, val_ds, model, num_classes)

# Save the figure to a file
fig.savefig(os.path.join(current_run_dir,"roc_training_validation.png"), dpi=300, bbox_inches='tight')

# Optionally display it
#plt.show()

# ----------------------------
# Count number of images in training and validation sets
# ----------------------------

num_train_images = count_images(train_ds)
num_val_images   = count_images(val_ds)

print(f"Number of training images: {num_train_images}")
print(f"Number of validation/testing images: {num_val_images}")

# Save the final model in the Keras format
model_save_path = os.path.join(current_run_dir, "skin_disease_model.keras")
model.save(model_save_path)

print(f"✅ Model saved successfully at: {model_save_path}")
